version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: roycedb
      POSTGRES_USER: axel
      POSTGRES_PASSWORD: 123asd
    ports:
      - "5432:5432"
  server:
    image: node-roycechallenge
    depends_on:
      - db
    ports:
      - "5000:5000"